### ISSUE TITLE
panic: BUG: Pool allocated rawPkt has incorrect size

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/server#109]
Not sure what I did here...
```
panic: BUG: Pool allocated rawPkt has incorrect size

goroutine 1384 [running]:
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).copyToRaw(0xc0c8866580, 0xc0c9d86000, 0xc9dc, 0xc9dc, 0x1c74ec0, 0xbf1b0a204a736ff4)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:177 +0x255
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.NewWithID(0xc0c9d86000, 0xc9dc, 0xc9dc, 0xd2, 0x42dc45, 0xc000041f80, 0xc0c7381cb0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:207 +0xa2
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.New(0xc0c9d86000, 0xc9dc, 0xc9dc, 0x3, 0x3, 0xc0c7381dd2)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:197 +0x74
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).onSendPacket(0xc0c7256cb0, 0xc0c9bbbba0, 0x0, 0x0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:398 +0x7c
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).onMixCommand(0xc0c7256cb0, 0x14a1ae0, 0xc0c9bbbba0, 0x2)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:302 +0x247
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).worker(0xc0c7256cb0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:287 +0xe65
created by github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/listener.go:109 +0x5d
exit status 2
```

**Comment by mixmasala** [comment]
also associated with a data race:
```
==================
WARNING: DATA RACE
Write at 0x00c0c8866580 by goroutine 213:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).copyToRaw()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:173 +0x158
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.NewWithID()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:207 +0xa1
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:197 +0x73
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).onSendPacket()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:398 +0x7b
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).onMixCommand()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:302 +0x246
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/incoming_conn.go:287 +0xe64

Previous read at 0x00c0c8866580 by goroutine 337:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).disposeRaw()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:187 +0x3e
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:145 +0x3c
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished.func3()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:283 +0xdc

Goroutine 213 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/listener.go:109 +0x5c
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/listener.go:112 +0x12e
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/listener.go:96 +0x319
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming.(*listener).worker-fm()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/incoming/listener.go:185 +0x41
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Goroutine 337 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:267 +0x7a7
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:198 +0xbe2
==================
==================
WARNING: DATA RACE
Write at 0x00c0c88665c0 by goroutine 58:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:152 +0xe0
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:183 +0x932
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker-fm()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x41
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c0c88665c0 by goroutine 337:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:152 +0xe0
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished.func3()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:283 +0xdc

Goroutine 58 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:36 +0xa8
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x37a
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/server.go:353 +0x1208
  github.com/katzenpost/kimchi.(*kimchi).Run()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi.go:135 +0x268
  github.com/katzenpost/kimchi.TestReliableDelivery()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi_test.go:434 +0x1ea
  testing.tRunner()
      /usr/lib/go-1.11/src/testing/testing.go:827 +0x162

Goroutine 337 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:267 +0x7a7
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:198 +0xbe2
==================
==================
WARNING: DATA RACE
Write at 0x00c0c88665c8 by goroutine 58:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:153 +0x10c
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:183 +0x932
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker-fm()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x41
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c0c88665c8 by goroutine 337:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:153 +0x10c
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished.func3()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:283 +0xdc

Goroutine 58 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:36 +0xa8
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x37a
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/server.go:353 +0x1208
  github.com/katzenpost/kimchi.(*kimchi).Run()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi.go:135 +0x268
  github.com/katzenpost/kimchi.TestReliableDelivery()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi_test.go:434 +0x1ea
  testing.tRunner()
      /usr/lib/go-1.11/src/testing/testing.go:827 +0x162

Goroutine 337 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:267 +0x7a7
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:198 +0xbe2
==================
==================
WARNING: DATA RACE
Write at 0x00c0c88665d8 by goroutine 58:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:155 +0x14d
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:183 +0x932
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.(*Worker).worker-fm()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x41
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c0c88665d8 by goroutine 337:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet.(*Packet).Dispose()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/packet/packet.go:155 +0x14d
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished.func3()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:283 +0xdc

Goroutine 58 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:36 +0xa8
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:314 +0x37a
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server.New()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/server.go:353 +0x1208
  github.com/katzenpost/kimchi.(*kimchi).Run()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi.go:135 +0x268
  github.com/katzenpost/kimchi.TestReliableDelivery()
      /home/user/go/src/github.com/katzenpost/kimchi/kimchi_test.go:434 +0x1ea
  testing.tRunner()
      /usr/lib/go-1.11/src/testing/testing.go:827 +0x162

Goroutine 337 (running) created at:
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).onConnEstablished()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:267 +0x7a7
  github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*outgoingConn).worker()
      /home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/outgoing_conn.go:198 +0xbe2
==================
```

**Comment by mixmasala** [comment]
seems fixed by: https://github.com/katzenpost/server/tree/fix_queue_pop
