### ISSUE TITLE
panic in DispatchPacket

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/server#111]
from testing with kimchi branch: https://github.com/katzenpost/kimchi/tree/add_warped_epoch_flag commit: bc0145e4cef5b2d019cb3c287c8a46d123effa69
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf22026]

goroutine 16 [running]:
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing.(*connector).DispatchPacket(0xc00016c500, 0xc060e8a200)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/outgoing/connector.go:69 +0xa6
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/scheduler.(*scheduler).worker(0xc00014c6c0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/scheduler/scheduler.go:192 +0x7f5
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/scheduler.(*scheduler).worker-fm()
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/server/internal/scheduler/scheduler.go:225 +0x42
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc00014c6c0, 0xc0001516a0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x5d
created by github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:36 +0xa9
exit status 2
FAIL	github.com/katzenpost/kimchi	165.785s
```

**Comment by mixmasala** [comment]
seems fixed by: https://github.com/katzenpost/server/tree/fix_queue_pop
