### ISSUE TITLE
cbor plugin system related panic: close of closed channel

### ISSUE THREAD

**Issue by david415** [katzenpost/server#119]
panic: close of closed channel

goroutine 55 [running]:
github.com/katzenpost/core/worker.(*Worker).Halt(0xc0000da5a0)
	/home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:46 +0x66
created by github.com/katzenpost/server/internal/provider/kaetzchen.(*CBORPluginWorker).haltAllClients
	/home/user/gopath/src/github.com/katzenpost/server/internal/provider/kaetzchen/cbor_plugins.go:112 +0x60

**Comment by david415** [comment]
fixed https://github.com/katzenpost/server/commit/956f21ff3f9e441af56e5816f77f9b5c134eadf6
