### ISSUE TITLE
receive packet without panic

### ISSUE THREAD

**Issue by david415** [Katzenpost/server#17]
```
panic: interface conversion: interface {} is []uint8, not *[]uint8

goroutine 301 [running]:
github.com/katzenpost/server.(*packet).copyToRaw(0xc4a1126750, 0xc4a13b0000, 0xc9dc, 0xc9dc, 0x0, 0x0)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/packet.go:128 +0x151
github.com/katzenpost/server.(*incomingConn).onSendPacket(0xc48043aeb0, 0xc4a10ad540, 0xc48054ffb8, 0x3)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:308 +0x57
github.com/katzenpost/server.(*incomingConn).onMixCommand(0xc48043aeb0, 0xa2e440, 0xc4a10ad540, 0xc48054fe0f)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:232 +0x219
github.com/katzenpost/server.(*incomingConn).worker(0xc48043aeb0)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:217 +0x899
created by github.com/katzenpost/server.(*listener).onNewConn.func1
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/listener.go:93 +0x53
```

**Comment by Yawning** [comment]
Fixed by 69363fa18d97ee6595ed33c8dc9ffd90999b7bce

**Comment by david415** [comment]
```
panic: interface conversion: interface {} is *[]uint8, not []uint8

goroutine 359 [running]:
github.com/katzenpost/server.(*packet).copyToRaw(0xc480453440, 0xc481086000, 0xc9dc, 0xc9dc, 0x0, 0x0)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/packet.go:128 +0x151
github.com/katzenpost/server.(*incomingConn).onSendPacket(0xc480457770, 0xc480c22fa0, 0xc480567fb8, 0x3)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:308 +0x57
github.com/katzenpost/server.(*incomingConn).onMixCommand(0xc480457770, 0xa2e440, 0xc480c22fa0, 0xc480567e0f)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:232 +0x219
github.com/katzenpost/server.(*incomingConn).worker(0xc480457770)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:217 +0x899
created by github.com/katzenpost/server.(*listener).onNewConn.func1
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/listener.go:93 +0x53
```

**Comment by Yawning** [comment]
Sigh, this should be fixed.  The pool allocator does odd things.
