### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/server#86]
voting server crashed with error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xf7a522]

goroutine 72 [running]:
github.com/katzenpost/server/internal/cryptoworker.(*Worker).UpdateMixKeys(...)
        /home/user/go/src/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:53
github.com/katzenpost/server.(*Server).reshadowCryptoWorkers(0xc42020e000)
        /home/user/go/src/github.com/katzenpost/server/server.go:100 +0xe2
github.com/katzenpost/server.(*serverGlue).ReshadowCryptoWorkers(0xc420196020)
        /home/user/go/src/github.com/katzenpost/server/server.go:450 +0x4a
github.com/katzenpost/server/internal/pki.(*pki).publishDescriptorIfNeeded(0xc4200d00a0, 0x12bf860, 0xc4201fe200, 0xc42013f700, 0x2)
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:368 +0x759
github.com/katzenpost/server/internal/pki.(*pki).worker(0xc4200d00a0)
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:175 +0xcf6
github.com/katzenpost/server/internal/pki.(*pki).(github.com/katzenpost/server/internal/pki.worker)-fm()
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:66 +0x42
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc4200d00b8, 0xc42006b170)
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:38 +0x5d
created by github.com/katzenpost/core/worker.(*Worker).Go
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:36 +0xc5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xf7a522]

goroutine 53 [running]:
github.com/katzenpost/server/internal/cryptoworker.(*Worker).UpdateMixKeys(...)
        /home/user/go/src/github.com/katzenpost/server/internal/cryptoworker/crypto_worker.go:53
github.com/katzenpost/server.(*Server).reshadowCryptoWorkers(0xc4200d61e0)
        /home/user/go/src/github.com/katzenpost/server/server.go:100 +0xe2
github.com/katzenpost/server.(*serverGlue).ReshadowCryptoWorkers(0xc42000e4b0)
        /home/user/go/src/github.com/katzenpost/server/server.go:450 +0x4a
github.com/katzenpost/server/internal/pki.(*pki).publishDescriptorIfNeeded(0xc4201ce0a0, 0x12bf860, 0xc4200857c0, 0xc420234400, 0x2)
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:368 +0x759
github.com/katzenpost/server/internal/pki.(*pki).worker(0xc4201ce0a0)
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:175 +0xcf6
github.com/katzenpost/server/internal/pki.(*pki).(github.com/katzenpost/server/internal/pki.worker)-fm()
        /home/user/go/src/github.com/katzenpost/server/internal/pki/pki.go:66 +0x42
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc4201ce0b8, 0xc42018ae20)
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:38 +0x5d
created by github.com/katzenpost/core/worker.(*Worker).Go
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:36 +0xc5
```

**Comment by hhalpin** [comment]
This issue was moved to katzenpost/mixnet_uprising#73
