### ISSUE TITLE
panic: wire/session: PeerCredentials() call in invalid state

### ISSUE THREAD

**Issue by david415** [katzenpost/server#97]
panic: wire/session: PeerCredentials() call in invalid state
```
goroutine 62 [running]:
github.com/katzenpost/core/wire.(*Session).PeerCredentials(0xc42c292a80, 0xdce620)
        /home/user/gopath/src/github.com/katzenpost/core/wire/session.go:431 +0x59
github.com/katzenpost/server/internal/incoming.(*incomingConn).onRetrieveMessage(0xc42c2be3f0, 0xc42c44c99c, 0x23, 0x0)
        /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:341 +0x16b
github.com/katzenpost/server/internal/incoming.(*incomingConn).worker(0xc42c2be3f0)
        /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:266 +0x970
created by github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1
        /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:109 +0x4f
```

**Comment by mixmasala** [comment]
Do you have a logfile or any messages before this panic?

**Comment by david415** [comment]
yes. here:

```
20:09:28.757 DEBU crypto:0: Packet: 2 (IsReplay took: 52.745µs)
20:09:28.757 DEBU crypto:0: Packet: 2 (doUnwrap took: 247.92µs)
20:09:28.757 DEBU crypto:0: Handing off user destined packet: 2
20:09:28.759 DEBU provider: Stored SURB-Reply: 2
20:09:36.429 DEBU incoming:3: Received RetrieveMessage from peer.
20:09:36.429 DEBU incoming:3: RetrieveMessage: 1
20:09:37.022 DEBU incoming:3: Failed to receive command: EOF
20:09:37.022 DEBU incoming:3: Received RetrieveMessage from peer.
20:09:37.022 DEBU incoming:3: RetriveMessage: 2 (Popping head)
20:09:37.022 DEBU incoming:3: Closing.

```

**Comment by mixmasala** [comment]
Problem seems to be that RecvCommand and SendCommand can both modify state, here's a branch using RWMutex to prevent modifying Session.state while another method has a reader lock.

https://github.com/katzenpost/core/tree/add_rwlock_to_session
