### ISSUE TITLE
bad kaetzchen query crashes and seg faults server

### ISSUE THREAD

**Issue by david415** [katzenpost/server#98]
server death upon bad query is a lame bug. we should fix it.

```
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: panic: runtime error: invalid memory address or nil pointer dereference                                          
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x950644]                                           
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:                                                                                                                  
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: goroutine 23 [running]:                                                                                          
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: gopkg.in/op/go-logging%2ev1.(*Logger).IsEnabledFor(0x0, 0x5, 0x8)                                                
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/gopkg.in/op/go-logging.v1/logger.go:132 +0x34                                        
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: gopkg.in/op/go-logging%2ev1.(*Logger).log(0x0, 0x5, 0xaf5961, 0x31, 0xc42022a720, 0x1, 0x1)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/gopkg.in/op/go-logging.v1/logger.go:136 +0x39
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: gopkg.in/op/go-logging%2ev1.(*Logger).Debugf(0x0, 0xaf5961, 0x31, 0xc42022a720, 0x1, 0x1)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/gopkg.in/op/go-logging.v1/logger.go:244 +0x66
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: github.com/katzenpost/server_plugins/currency/proxy.(*Currency).OnRequest(0xc4200b1e60, 0x1, 0xc4202c4000, 0xc5d$
, 0xe000, 0x1, 0xa5f1c0, 0xc420136f80, 0xc42005da40, 0x410063, ...)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/github.com/katzenpost/server_plugins/currency/proxy/proxy.go:51 +0xee
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: github.com/katzenpost/server/plugin.(*GRPCServer).OnRequest(0xc42022a420, 0xb65b40, 0xc420165350, 0xc420165380, $
xc42022a420, 0xc4201652c0, 0x9fc0e0)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/github.com/katzenpost/server/plugin/grpc.go:34 +0x7b
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: github.com/katzenpost/server/plugin/proto._Kaetzchen_OnRequest_Handler(0x9fe4e0, 0xc42022a420, 0xb65b40, 0xc4201$
5350, 0xc420160690, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/github.com/katzenpost/server/plugin/proto/kaetzchen.pb.go:176 +0x241
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: google.golang.org/grpc.(*Server).processUnaryRPC(0xc420234000, 0xb67e80, 0xc42025e000, 0xc4200fa500, 0xc420164f3$
, 0xe2b1e0, 0x0, 0x0, 0x0)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/google.golang.org/grpc/server.go:994 +0x4f9
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: google.golang.org/grpc.(*Server).handleStream(0xc420234000, 0xb67e80, 0xc42025e000, 0xc4200fa500, 0x0)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/google.golang.org/grpc/server.go:1220 +0x1318
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420024c20, 0xc420234000, 0xb67e80, 0xc42025e000, 0xc420$
fa500)
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/google.golang.org/grpc/server.go:688 +0x9f
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency: created by google.golang.org/grpc.(*Server).serveStreams.func1
2018-12-10T01:28:37.864Z [DEBUG] plugin.currency:       /home/user/gopath/src/google.golang.org/grpc/server.go:686 +0xa1
2018-12-10T01:28:37.864Z [DEBUG] plugin: plugin process exited: path=/home/admin/bin/currency
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa50256]

goroutine 53 [running]:
github.com/katzenpost/server/plugin.(*GRPCClient).OnRequest(0xc4202065e0, 0x1, 0xc43039e23e, 0xc5d2, 0xc5d2, 0x201, 0xc7fe, 0x0, 0x0, 0xc42c266d00, ...)
        /home/user/gopath/src/github.com/katzenpost/server/plugin/grpc.go:62 +0xe6
github.com/katzenpost/server/internal/provider/kaetzchen.(*PluginKaetzchenWorker).processKaetzchen(0xc42019e310, 0xc420188400, 0x7f10a9ef8d10, 0xc4202065e0)
        /home/user/gopath/src/github.com/katzenpost/server/internal/provider/kaetzchen/plugins.go:117 +0x21b
github.com/katzenpost/server/internal/provider/kaetzchen.(*PluginKaetzchenWorker).worker(0xc42019e310, 0x63657a2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f10a9ef8d1
0, ...)
        /home/user/gopath/src/github.com/katzenpost/server/internal/provider/kaetzchen/plugins.go:97 +0x3b8
github.com/katzenpost/server/internal/provider/kaetzchen.NewPluginKaetzchenWorker.func1()
        /home/user/gopath/src/github.com/katzenpost/server/internal/provider/kaetzchen/plugins.go:296 +0x58
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc42019e318, 0xc42020a4e0)
        /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x4f
created by github.com/katzenpost/core/worker.(*Worker).Go
        /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:36 +0x93

```

**Comment by mixmasala** [comment]
Do you have the logfiles from this run?

**Comment by david415** [comment]
no but i can easily reproduce this behavior at any time by simply writing a gRPC plugin that panics.
